LIBRARY ieee;
USE ieee.std_logic_1164.ALL;

PACKAGE sd_file_pkg IS
    CONSTANT SD_BROWSER_MAX_FILES : INTEGER := 255;
    CONSTANT SD_BROWSER_LAST_INDEX : INTEGER := SD_BROWSER_MAX_FILES - 1;
    CONSTANT SD_BROWSER_PAGE_SIZE : INTEGER := 10;
    CONSTANT SD_BROWSER_PAGE_LAST : INTEGER := SD_BROWSER_PAGE_SIZE - 1;
    TYPE sd_valid_array_t IS ARRAY (0 TO SD_BROWSER_LAST_INDEX) OF STD_LOGIC;
    TYPE sd_name_array_t IS ARRAY (0 TO SD_BROWSER_LAST_INDEX) OF STD_LOGIC_VECTOR(87 DOWNTO 0);
    TYPE sd_cluster_array_t IS ARRAY (0 TO SD_BROWSER_LAST_INDEX) OF STD_LOGIC_VECTOR(31 DOWNTO 0);
    TYPE sd_size_array_t IS ARRAY (0 TO SD_BROWSER_LAST_INDEX) OF STD_LOGIC_VECTOR(31 DOWNTO 0);
    TYPE sd_page_valid_array_t IS ARRAY (0 TO SD_BROWSER_PAGE_LAST) OF STD_LOGIC;
    TYPE sd_page_name_array_t IS ARRAY (0 TO SD_BROWSER_PAGE_LAST) OF STD_LOGIC_VECTOR(87 DOWNTO 0);
    TYPE sd_kind_array_t IS ARRAY (0 TO SD_BROWSER_LAST_INDEX) OF STD_LOGIC_VECTOR(1 DOWNTO 0);
    TYPE sd_page_kind_array_t IS ARRAY (0 TO SD_BROWSER_PAGE_LAST) OF STD_LOGIC_VECTOR(1 DOWNTO 0);
    CONSTANT SD_DSK_KIND_UNKNOWN : STD_LOGIC_VECTOR(1 DOWNTO 0) := "00";
    CONSTANT SD_DSK_KIND_CPM     : STD_LOGIC_VECTOR(1 DOWNTO 0) := "01";
    CONSTANT SD_DSK_KIND_NASSYS  : STD_LOGIC_VECTOR(1 DOWNTO 0) := "10";
END PACKAGE;

PACKAGE BODY sd_file_pkg IS
END PACKAGE BODY;
